# Generated by Django 4.0.5 on 2022-08-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('atm', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('cvv', models.IntegerField(max_length=3)),
            ],
        ),
    ]
