# Generated by Django 4.0.5 on 2022-08-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RechargeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='atm',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
