# Generated by Django 4.0.5 on 2022-08-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RechargeAPI', '0002_alter_userdetails_atm_alter_userdetails_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='atmpin',
            field=models.CharField(default='', max_length=6),
        ),
    ]
