# Generated by Django 4.0.4 on 2022-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('phone_no', models.CharField(max_length=10)),
                ('query', models.TextField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='descr',
            field=models.TextField(default='Not Added'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
