# Generated by Django 4.0.4 on 2022-04-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_contacts_user_descr_alter_user_dob_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='ContactsInfo',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
    ]
