# Generated by Django 4.0.4 on 2022-04-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_rename_contacts_contactsinfo_rename_user_userdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='userDetail',
        ),
    ]
