# Generated by Django 4.0.4 on 2022-04-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_remove_contactsinfo_id_remove_userdetail_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(default='Already Exists', max_length=200, primary_key=True, serialize=False),
        ),
    ]
